### ISSUE TITLE
Request to Integrate HuggingFace Accelerate or DeepSpeed to Address CUDA Memory Issues

### ISSUE THREAD

**Issue by koanho** [arcee-ai/DAM#47]
Hi,

Thank you for sharing this amazing work! I really appreciate the effort you have put into this project.

I would like to request consideration for integrating HuggingFace Accelerate or [DeepSpeed](https://www.deepspeed.ai/) into the code. I have encountered a CUDA out of memory issue when trying to merge two Llama models (3.1B and 70B) while working with 8x A100 GPUs.

If you are open to it, I would be happy to assist with further testing or provide additional details about the issue I encountered.

Thank you for considering this request!

**Comment by shamanez** [comment]
Actually I tried to set it up. For some reason deepspeed coudn't work with our settings since the model had around 23B parameters.

**Comment by koanho** [comment]
Thank you for your response. I'll try for it.
